name: Deploy to Azure Container Apps

on:
  workflow_dispatch: 
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: carmechanicregistry
  IMAGE_NAME: carmechanicwebapi
  RESOURCE_GROUP: car-mechanic-dev

jobs:
  publish: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore 
        run: dotnet restore ./CarMechanic.WebAPI.sln

      - name: Build
        run: dotnet build ./CarMechanic.WebAPI.sln --configuration Release --no-restore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      
      - name: Build docker image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f ./CarMechanic.WebAPI/Dockerfile .

      - name: Push docker image
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
        
